//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageVisualiser.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConsoleOutput {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleOutput() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageVisualiser.Resources.ConsoleOutput", typeof(ConsoleOutput).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image compression ratio (1 - original, 2 - 2x compression, etc.).
        /// </summary>
        public static string CompressionRatioPropertyKey {
            get {
                return ResourceManager.GetString("CompressionRatioPropertyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can not be empty!.
        /// </summary>
        public static string EmptyValueException {
            get {
                return ResourceManager.GetString("EmptyValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR].
        /// </summary>
        public static string ErrorTag {
            get {
                return ResourceManager.GetString("ErrorTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image path.
        /// </summary>
        public static string ImagePathPropertyKey {
            get {
                return ResourceManager.GetString("ImagePathPropertyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INITIALIZATION].
        /// </summary>
        public static string InitializationTag {
            get {
                return ResourceManager.GetString("InitializationTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can not be negative!.
        /// </summary>
        public static string NegativeValueException {
            get {
                return ResourceManager.GetString("NegativeValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualization symbol.
        /// </summary>
        public static string OutputSymbolPropertyKey {
            get {
                return ResourceManager.GetString("OutputSymbolPropertyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization completed successfully, parameters set.
        /// </summary>
        public static string SuccessfulInitialization {
            get {
                return ResourceManager.GetString("SuccessfulInitialization", resourceCulture);
            }
        }
    }
}
